export const CLOSE_ERR_MSG = 'CLOSE_ERR_MSG'
export const CLOSE_SUCCESS_MSG = 'CLOSE_SUCCESS_MSG';

/**********ORG************/
export const SHOW_NEW_ORG = 'SHOW_NEW_ORG';
export const CANCEL_NEW_ORG = 'CANCEL_NEW_ORG';

export const LOAD_ORG = 'LOAD_ORG';
export const LOAD_ORG_SUCCESS = 'LOAD_ORG_SUCCESS';
export const LOAD_ORG_FAIL = 'LOAD_ORG_FAIL';

export const CREATE_ORG = 'CREATE_ORG';
export const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS';
export const CREATE_ORG_FAIL = 'LOAD_ORG_FAIL';

/**********GYM************/
export const LOAD_GYM = 'LOAD_GYM';
export const LOAD_GYM_SUCCESS = 'LOAD_GYM_SUCCESS';
export const LOAD_GYM_FAIL = 'LOAD_GYM_FAIL';

export const CREATE_GYM = 'CREATE_GYM';
export const CREATE_GYM_SUCCESS = 'CREATE_GYM_SUCCESS';
export const CREATE_GYM_FAIL = 'CREATE_GYM_FAIL';

export const UPDATE_GYM = 'UPDATE_GYM';
export const UPDATE_GYM_SUCCESS = 'UPDATE_GYM_SUCCESS';
export const UPDATE_GYM_FAIL = 'UPDATE_GYM_FAIL';

export const SHOW_NEW_GYM = 'SHOW_NEW_GYM';
export const CANCEL_NEW_GYM = 'CANCEL_NEW_GYM';

/**********HEADER************/
export const SWITCH_GYM = 'SWITCH_GYM';
export const LOAD_LOGGED_IN_COACH_INFO = 'LOAD_LOGGED_IN_COACH_INFO';
export const LOAD_LOGGED_IN_COACH_INFO_SUCCESS = 'LOAD_LOGGED_IN_COACH_INFO_SUCCESS';
export const LOAD_LOGGED_IN_COACH_INFO_FAIL = 'LOAD_LOGGED_IN_COACH_INFO_FAIL';

/**********COACH************/
export const SHOW_NEW_COACH = 'SHOW_NEW_COACH';
export const CANCEL_NEW_COACH = 'CANCEL_NEW_COACH';
export const CREATE_COACH = 'CREATE_COACH';
export const CREATE_COACH_SUCCESS = 'CREATE_COACH_SUCCESS';
export const CREATE_COACH_FAIL = 'CREATE_COACH_FAIL';
export const LOAD_COACH = 'LOAD_COACH';
export const LOAD_COACH_SUCCESS = 'LOAD_COACH_SUCCESS';
export const LOAD_COACH_FAIL = 'LOAD_COACH_FAIL';
export const DELETE_COACH = 'DELETE_COACH';
export const DELETE_COACH_SUCCESS = 'DELETE_COACH_SUCCESS';
export const DELETE_COACH_FAIL = 'DELETE_COACH_FAIL';

/**********ORDER************/
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const SHOW_NEW_ORDER = 'SHOW_NEW_ORDER';
export const CANCEL_NEW_ORDER = 'CANCEL_NEW_ORDER';

/**********CUSTOMER************/
export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';
export const LOAD_CUSTOMER_SUCCESS = 'LOAD_CUSTOMER_SUCCESS';
export const LOAD_CUSTOMER_FAIL = 'LOAD_CUSTOMER_FAIL';